### ISSUE TITLE
display_driver issue.

### ISSUE THREAD

**Issue by njordan77** [djaffry/oeffis-paper#4]
Sorry, me again, did pull the latest release. Setup now runs smoothly. but start.sh simply does not show anything - except saying that PID already running. did kill.sh and start.sh...but again same error message. So looked into the start script and did run the following manually to see error logs:

Any clue what still is wrong....do i have to prepare the epaper display with driver setup upfront.....??

pi@InfoScreen:~/oeffis-paper $  venv/bin/python3 main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from display.display_driver import UIDriver
  File "/home/pi/oeffis-paper/display/display_driver.py", line 5, in <module>
    from lib.waveshare.epd7in5b import EPD
  File "/home/pi/oeffis-paper/lib/waveshare/epd7in5b.py", line 51, in <module>
    from lib.waveshare import epdconfig
  File "/home/pi/oeffis-paper/lib/waveshare/epdconfig.py", line 48, in <module>
    SPI = spidev.SpiDev(0, 0)
FileNotFoundError: [Errno 2] No such file or directory

**Comment by djaffry** [comment]
> Sorry, me again, did pull the latest release. Setup now runs smoothly. but start.sh simply does not show anything - except saying that PID already running. did kill.sh and start.sh...but again same error message.

have a look into your scripts folder and confirm that there's no `current_pid.txt` there. If there's one, just delete it. If you still experience problems, I would recommend you to clone the project anew and run the `setup.sh` again.

> Btw. if you haven't done already, you need to activate SPI on your raspberry pi too so the pi can communicate to the e-paper screen. It's part of the e-paper setup process. [howto](https://www.raspberrypi.org/documentation/configuration/raspi-config.md)

Have you done this? You need to enable the SPI on the pi.

**Comment by njordan77** [comment]
Thanks a lot! It was the SPI disabled-issue. I now saw that you even wrote this in the HW part of your documentation. SORRY.

Now i'm another step closer to FINISHED, the display refreshes few times like epaper does, in the end it writes HTTPError: 555 Server Error: unknown for url.....tickes.oebb.at/api/hafas/vtimetable......traceback main.py line 114 .....

As a starter i only changed/inserted my WrLinien Key in the JSON config file.....

Regards Norbert

**Comment by djaffry** [comment]
> Thanks a lot! It was the SPI disabled-issue. I now saw that you even wrote this in the HW part of your documentation. SORRY.

Hey, it's alright! Happy to help!

> Now i'm another step closer to FINISHED, the display refreshes few times like epaper does, in the end it writes HTTPError: 555 Server Error: unknown for url.....tickes.oebb.at/api/hafas/vtimetable......traceback main.py line 114 .....

Yeah. There seems to be issues with retrieving data from the ÖBB endpoint. There's no official ÖBB API yet and they changed their endpoint again. I'm already working on it :)

**Comment by njordan77** [comment]
oh thanks....i had similar experience with Wr.Linien - not sure if i did see it correctly but WrLinien changed JSON format several times

Is there a way to simply omit OEBB. Tried to remove it from config.json but still stops with errors in the display. Can you tell me please what needs to be removed to only see Wr.Linien ?

**Comment by njordan77** [comment]
hey there, sorry to bother again. did you have time to look into this? as written - is there a simple way to disable OEBB so i would only have the WrLinien display part - which is my biggest interrest area.

Cheers,Norbert

**Comment by djaffry** [comment]
Hi Norbert!

So I fixed the OeBB endpoint connection in [commit 1c77d8f](https://github.com/djaffry/oeffis-paper/commit/1c77d8ffdd9dd6e0f6a675316cc99ddd79a4726d). Should all be working now.
Some dependencies changed, so you have to run the setup script again.

The most recent [commit 9a3136a](https://github.com/djaffry/oeffis-paper/commit/9a3136a8f15e35c8b83dfff54466b00719a52bfa) makes all APIs optional, so you should be fine if you omit the `oebb` section in `config.json`.

Let me know if everything works for you now :)

**Comment by njordan77** [comment]
thanks a lot for your effort!!!! I tried the git pull & re-setup.sh but after starting the script the display updates and only shows error messages on the epaper display
KeyError traceback main.py line 133......display_driver.py line 25....keyerror 'lines'.

I kept our config.json and simply used my WrLinien key that works at least in the firefox browser. Cheers Norbert

**Comment by djaffry** [comment]
Hmm strange. Could you please modify your `utils.py` and revert this change back to `logger.setLevel(logging.DEBUG)`, run it again and send me the log?

![image](https://user-images.githubusercontent.com/5738259/76945634-17014900-6903-11ea-9df1-e4eca2bfcf19.png)

**Comment by njordan77** [comment]
Hi, thanks a lot for further looking into my problem:
i hope you mean the nuhup.out file by logfile.

```
2020-03-19 22:11:00,168 - INFO - __main__:  Application Start!
e-Paper busy
e-Paper busy release
2020-03-19 22:11:00,671 - INFO - __main__:  Cycle Start!
2020-03-19 22:11:20,394 - INFO - __main__:  Traffic Data: {'stations': [{'lines': [{'name': '11A', 'direction': 'Bhf. Heiligenstadt S U', 'barrierFree': True, 'trafficJam': False, 'departures': [11, 26, 41, 56]}], 'name': 'Vorgartenstra$
2020-03-19 22:11:20,395 - ERROR - __main__:  First time catching KeyError
2020-03-19 22:11:22,397 - INFO - __main__:  Cycle Start!
2020-03-19 22:11:40,325 - INFO - __main__:  Traffic Data: {'stations': [{'lines': [{'name': '11A', 'direction': 'Bhf. Heiligenstadt S U', 'barrierFree': True, 'trafficJam': False, 'departures': [10, 25, 40, 55]}], 'name': 'Vorgartenstra$
e-Paper busy
e-Paper busy release
Vertical
Vertical
e-Paper busy
e-Paper busy release
Traceback (most recent call last):
  File "main.py", line 176, in <module>
    main()
  File "main.py", line 165, in main
    raise err
  File "main.py", line 133, in main
    ui_driver.display(traffic_data, yrno_data)
  File "/home/pi/oeffis-paper/display/display_driver.py", line 25, in display
    traffic_data = self._adjust_to_render_offset(traffic_data)
  File "/home/pi/oeffis-paper/display/display_driver.py", line 70, in _adjust_to_render_offset
    for l in s['lines']:
KeyError: 'lines'

![IMG_2528](https://user-images.githubusercontent.com/7437150/77119871-ae67b880-6a37-11ea-897d-6b94fdf3e13d.JPG)

```
